name: studify
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6

  # Firebase (all same generation)
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4

  # Other packages
  google_sign_in: ^6.2.1
  supabase_flutter: ^2.10.3
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.6
  image_picker: ^1.2.1
  file_picker: ^8.0.0
  flutter_local_notifications: ^19.5.0
  app_settings: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/studify.png"

flutter:
  uses-material-design: true

  assets:
    - assets/studify.png
    - assets/profile.jpeg

  fonts:
    - family: StackSansText
      fonts:
        - asset: assets/fonts/StackSansText-Bold.ttf
